/**
 * La división político-territorial de Venezuela, para el destino de un envío.
 *
 * Va dentro del repo y no detrás de una API. Un checkout que depende de un
 * servicio ajeno deja de vender el día que ese servicio se cae, y esto son
 * 24 estados y 480 ciudades que cambian una vez cada década: no hay nada
 * que ir a consultar.
 *
 * Estado y ciudad, sin municipio en medio: es lo que pide una encomienda para
 * cotizar el flete. Y una ciudad no cuelga de un municipio —Caracas misma está
 * repartida entre varios—, así que encadenarlos sería inventarse un vínculo
 * que no existe.
 *
 * Sale de github.com/zokeber/venezuela-json, con dos correcciones: Vargas pasó
 * a llamarse La Guaira en 2019 y allí sigue con el nombre viejo, y Distrito
 * Capital venía sin ciudades.
 *
 * Los nombres se dejan tal cual vienen, con su desambiguación incluida
 * («Píritu Falcón», «Chaguaramas Guárico»): quitarla a mano se llevaría por
 * delante los que la tienen de verdad, como Ciudad Bolívar.
 */

export type EstadoVenezolano = {
  nombre: string;
  /** En orden alfabético, que es como se busca en una lista larga. */
  ciudades: string[];
};

export const ESTADOS: EstadoVenezolano[] = [
  {
    nombre: "Amazonas",
    ciudades: [
      "Maroa",
      "Puerto Ayacucho",
      "San Fernando de Atabapo",
    ],
  },
  {
    nombre: "Anzoátegui",
    ciudades: [
      "Anaco",
      "Aragua de Barcelona",
      "Barcelona",
      "Boca de Uchire",
      "Cantaura",
      "Clarines",
      "El Chaparro",
      "El Pao Anzoátegui",
      "El Tigre",
      "El Tigrito",
      "Guanape",
      "Guanta",
      "Lechería",
      "Onoto",
      "Pariaguán",
      "Píritu",
      "Puerto La Cruz",
      "Puerto Píritu",
      "Sabana de Uchire",
      "San Mateo Anzoátegui",
      "San Pablo Anzoátegui",
      "San Tomé",
      "Santa Ana de Anzoátegui",
      "Santa Fe Anzoátegui",
      "Santa Rosa",
      "Soledad",
      "Urica",
      "Valle de Guanape",
    ],
  },
  {
    nombre: "Apure",
    ciudades: [
      "Achaguas",
      "Biruaca",
      "Bruzual",
      "El Amparo",
      "El Nula",
      "Elorza",
      "Guasdualito",
      "Mantecal",
      "Puerto Páez",
      "San Fernando de Apure",
      "San Juan de Payara",
    ],
  },
  {
    nombre: "Aragua",
    ciudades: [
      "Barbacoas",
      "Cagua",
      "Camatagua",
      "Choroní",
      "Colonia Tovar",
      "El Consejo",
      "La Victoria",
      "Las Tejerías",
      "Magdaleno",
      "Maracay",
      "Ocumare de La Costa",
      "Palo Negro",
      "San Casimiro",
      "San Mateo",
      "San Sebastián",
      "Santa Cruz de Aragua",
      "Tocorón",
      "Turmero",
      "Villa de Cura",
      "Zuata",
    ],
  },
  {
    nombre: "Barinas",
    ciudades: [
      "Barinas",
      "Barinitas",
      "Barrancas",
      "Calderas",
      "Capitanejo",
      "Ciudad Bolivia",
      "El Cantón",
      "Las Veguitas",
      "Libertad de Barinas",
      "Sabaneta",
      "Santa Bárbara de Barinas",
      "Socopó",
    ],
  },
  {
    nombre: "Bolívar",
    ciudades: [
      "Caicara del Orinoco",
      "Canaima",
      "Ciudad Bolívar",
      "Ciudad Piar",
      "El Callao",
      "El Dorado",
      "El Manteco",
      "El Palmar",
      "El Pao",
      "Guasipati",
      "Guri",
      "La Paragua",
      "Matanzas",
      "Puerto Ordaz",
      "San Félix",
      "Santa Elena de Uairén",
      "Tumeremo",
      "Unare",
      "Upata",
    ],
  },
  {
    nombre: "Carabobo",
    ciudades: [
      "Bejuma",
      "Belén",
      "Campo de Carabobo",
      "Canoabo",
      "Central Tacarigua",
      "Chirgua",
      "Ciudad Alianza",
      "El Palito",
      "Guacara",
      "Guigue",
      "Las Trincheras",
      "Los Guayos",
      "Mariara",
      "Miranda",
      "Montalbán",
      "Morón",
      "Naguanagua",
      "Puerto Cabello",
      "San Joaquín",
      "Tocuyito",
      "Urama",
      "Valencia",
      "Vigirimita",
    ],
  },
  {
    nombre: "Cojedes",
    ciudades: [
      "Aguirre",
      "Apartaderos Cojedes",
      "Arismendi",
      "Camuriquito",
      "El Baúl",
      "El Limón",
      "El Pao Cojedes",
      "El Socorro",
      "La Aguadita",
      "Las Vegas",
      "Libertad de Cojedes",
      "Mapuey",
      "Piñedo",
      "Samancito",
      "San Carlos",
      "Sucre",
      "Tinaco",
      "Tinaquillo",
      "Vallecito",
    ],
  },
  {
    nombre: "Delta Amacuro",
    ciudades: [
      "Tucupita",
    ],
  },
  {
    nombre: "Distrito Capital",
    ciudades: [
      "Caracas",
    ],
  },
  {
    nombre: "Falcón",
    ciudades: [
      "Adícora",
      "Boca de Aroa",
      "Cabure",
      "Capadare",
      "Capatárida",
      "Chichiriviche",
      "Churuguara",
      "Coro",
      "Cumarebo",
      "Dabajuro",
      "Judibana",
      "La Cruz de Taratara",
      "La Vela de Coro",
      "Los Taques",
      "Maparari",
      "Mene de Mauroa",
      "Mirimire",
      "Pedregal",
      "Píritu Falcón",
      "Pueblo Nuevo Falcón",
      "Puerto Cumarebo",
      "Punta Cardón",
      "Punto Fijo",
      "San Juan de Los Cayos",
      "San Luis",
      "Santa Ana Falcón",
      "Santa Cruz De Bucaral",
      "Tocopero",
      "Tocuyo de La Costa",
      "Tucacas",
      "Yaracal",
    ],
  },
  {
    nombre: "Guárico",
    ciudades: [
      "Altagracia de Orituco",
      "Cabruta",
      "Calabozo",
      "Camaguán",
      "Chaguaramas Guárico",
      "El Socorro",
      "El Sombrero",
      "Las Mercedes de Los Llanos",
      "Lezama",
      "Onoto",
      "Ortíz",
      "San José de Guaribe",
      "San Juan de Los Morros",
      "San Rafael de Laya",
      "Santa María de Ipire",
      "Tucupido",
      "Valle de La Pascua",
      "Zaraza",
    ],
  },
  {
    nombre: "La Guaira",
    ciudades: [
      "Carayaca",
      "Litoral",
    ],
  },
  {
    nombre: "Lara",
    ciudades: [
      "Aguada Grande",
      "Atarigua",
      "Barquisimeto",
      "Bobare",
      "Cabudare",
      "Carora",
      "Cubiro",
      "Cují",
      "Duaca",
      "El Manzano",
      "El Tocuyo",
      "Guaríco",
      "Humocaro Alto",
      "Humocaro Bajo",
      "La Miel",
      "Moroturo",
      "Quíbor",
      "Río Claro",
      "Sanare",
      "Santa Inés",
      "Sarare",
      "Siquisique",
      "Tintorero",
    ],
  },
  {
    nombre: "Mérida",
    ciudades: [
      "Apartaderos Mérida",
      "Arapuey",
      "Bailadores",
      "Caja Seca",
      "Canaguá",
      "Chachopo",
      "Chiguara",
      "Ejido",
      "El Vigía",
      "La Azulita",
      "La Playa",
      "Lagunillas Mérida",
      "Mérida",
      "Mesa de Bolívar",
      "Mucuchíes",
      "Mucujepe",
      "Mucuruba",
      "Nueva Bolivia",
      "Palmarito",
      "Pueblo Llano",
      "Santa Cruz de Mora",
      "Santa Elena de Arenales",
      "Santo Domingo",
      "Tabáy",
      "Timotes",
      "Torondoy",
      "Tovar",
      "Tucani",
      "Zea",
    ],
  },
  {
    nombre: "Miranda",
    ciudades: [
      "Araguita",
      "Carrizal",
      "Caucagua",
      "Chaguaramas Miranda",
      "Charallave",
      "Chirimena",
      "Chuspa",
      "Cúa",
      "Cupira",
      "Curiepe",
      "El Guapo",
      "El Jarillo",
      "Filas de Mariche",
      "Guarenas",
      "Guatire",
      "Higuerote",
      "Los Anaucos",
      "Los Teques",
      "Ocumare del Tuy",
      "Panaquire",
      "Paracotos",
      "Río Chico",
      "San Antonio de Los Altos",
      "San Diego de Los Altos",
      "San Fernando del Guapo",
      "San Francisco de Yare",
      "San José de Los Altos",
      "San José de Río Chico",
      "San Pedro de Los Altos",
      "Santa Lucía",
      "Santa Teresa",
      "Tacarigua de La Laguna",
      "Tacarigua de Mamporal",
      "Tácata",
      "Turumo",
    ],
  },
  {
    nombre: "Monagas",
    ciudades: [
      "Aguasay",
      "Aragua de Maturín",
      "Barrancas del Orinoco",
      "Caicara de Maturín",
      "Caripe",
      "Caripito",
      "Chaguaramal",
      "Chaguaramas Monagas",
      "El Furrial",
      "El Tejero",
      "Jusepín",
      "La Toscana",
      "Maturín",
      "Miraflores",
      "Punta de Mata",
      "Quiriquire",
      "San Antonio de Maturín",
      "San Vicente Monagas",
      "Santa Bárbara",
      "Temblador",
      "Teresen",
      "Uracoa",
    ],
  },
  {
    nombre: "Nueva Esparta",
    ciudades: [
      "Altagracia",
      "Boca de Pozo",
      "Boca de Río",
      "El Espinal",
      "El Valle del Espíritu Santo",
      "El Yaque",
      "Juangriego",
      "La Asunción",
      "La Guardia",
      "Pampatar",
      "Porlamar",
      "Puerto Fermín",
      "Punta de Piedras",
      "San Francisco de Macanao",
      "San Juan Bautista",
      "San Pedro de Coche",
      "Santa Ana de Nueva Esparta",
      "Villa Rosa",
    ],
  },
  {
    nombre: "Portuguesa",
    ciudades: [
      "Acarigua",
      "Agua Blanca",
      "Araure",
      "Biscucuy",
      "Boconoito",
      "Campo Elías",
      "Chabasquén",
      "Guanare",
      "Guanarito",
      "La Aparición",
      "La Misión",
      "Mesa de Cavacas",
      "Ospino",
      "Papelón",
      "Payara",
      "Pimpinela",
      "Píritu de Portuguesa",
      "San Rafael de Onoto",
      "Santa Rosalía",
      "Turén",
    ],
  },
  {
    nombre: "Sucre",
    ciudades: [
      "Altos de Sucre",
      "Araya",
      "Cariaco",
      "Carúpano",
      "Casanay",
      "Cumaná",
      "Cumanacoa",
      "El Morro Puerto Santo",
      "El Pilar",
      "El Poblado",
      "Guaca",
      "Guiria",
      "Irapa",
      "Manicuare",
      "Mariguitar",
      "Río Caribe",
      "San Antonio del Golfo",
      "San José de Aerocuar",
      "San Vicente de Sucre",
      "Santa Fe de Sucre",
      "Tunapuy",
      "Yaguaraparo",
      "Yoco",
    ],
  },
  {
    nombre: "Táchira",
    ciudades: [
      "Abejales",
      "Borota",
      "Bramon",
      "Capacho",
      "Colón",
      "Coloncito",
      "Cordero",
      "El Cobre",
      "El Pinal",
      "Independencia",
      "La Fría",
      "La Grita",
      "La Pedrera",
      "La Tendida",
      "Las Delicias",
      "Las Hernández",
      "Lobatera",
      "Michelena",
      "Palmira",
      "Pregonero",
      "Queniquea",
      "Rubio",
      "San Antonio del Tachira",
      "San Cristobal",
      "San José de Bolívar",
      "San Josecito",
      "San Pedro del Río",
      "Santa Ana Táchira",
      "Seboruco",
      "Táriba",
      "Umuquena",
    ],
  },
  {
    nombre: "Trujillo",
    ciudades: [
      "Batatal",
      "Betijoque",
      "Boconó",
      "Carache",
      "Chejende",
      "Cuicas",
      "El Dividive",
      "El Jaguito",
      "Escuque",
      "Isnotú",
      "Jajó",
      "La Ceiba",
      "La Concepción de Trujllo",
      "La Mesa de Esnujaque",
      "La Puerta",
      "La Quebrada",
      "Mendoza Fría",
      "Meseta de Chimpire",
      "Monay",
      "Motatán",
      "Pampán",
      "Pampanito",
      "Sabana de Mendoza",
      "San Lázaro",
      "Santa Ana de Trujillo",
      "Tostós",
      "Trujillo",
      "Valera",
    ],
  },
  {
    nombre: "Yaracuy",
    ciudades: [
      "Aroa",
      "Boraure",
      "Campo Elías de Yaracuy",
      "Chivacoa",
      "Cocorote",
      "Farriar",
      "Guama",
      "Marín",
      "Nirgua",
      "Sabana de Parra",
      "Salom",
      "San Felipe",
      "San Pablo de Yaracuy",
      "Urachiche",
      "Yaritagua",
      "Yumare",
    ],
  },
  {
    nombre: "Zulia",
    ciudades: [
      "Bachaquero",
      "Bobures",
      "Cabimas",
      "Campo Concepción",
      "Campo Mara",
      "Campo Rojo",
      "Carrasquero",
      "Casigua",
      "Chiquinquirá",
      "Ciudad Ojeda",
      "El Batey",
      "El Carmelo",
      "El Chivo",
      "El Guayabo",
      "El Mene",
      "El Venado",
      "Encontrados",
      "Gibraltar",
      "Isla de Toas",
      "La Concepción",
      "La Paz",
      "La Sierrita",
      "Lagunillas",
      "Las Piedras",
      "Los Cortijos",
      "Machiques",
      "Maracaibo",
      "Mene Grande",
      "Palmarejo",
      "Paraguaipoa",
      "Potrerito",
      "Pueblo Nuevo",
      "Puertos de Altagracia",
      "Punta Gorda",
      "Sabaneta de Palma",
      "San Francisco",
      "San José de Perijá",
      "San Rafael del Moján",
      "San Timoteo",
      "Santa Bárbara del Zulia",
      "Santa Cruz de Mara",
      "Santa Cruz del Zulia",
      "Santa Rita",
      "Sinamaica",
      "Tamare",
      "Tía Juana",
      "Villa Rosario",
    ],
  },
];

/** Las ciudades de un estado. Vacío si el nombre no es de ninguno. */
export function ciudadesDe(estado: string): string[] {
  return ESTADOS.find((e) => e.nombre === estado)?.ciudades ?? [];
}

/**
 * Si esa ciudad es de ese estado.
 *
 * Lo comprueba el servidor antes de guardar: los dos campos llegan del
 * navegador y un destino inventado manda la encomienda a ninguna parte.
 */
export function esDestinoValido(estado: string, ciudad: string): boolean {
  return ciudadesDe(estado).includes(ciudad);
}
